-- =====================================================
-- MIGRATION 005: Add missing columns + notifications table
-- =====================================================

-- profils missing columns
ALTER TABLE profils ADD COLUMN IF NOT EXISTS telephone TEXT;
ALTER TABLE profils ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT FALSE;
ALTER TABLE profils ADD COLUMN IF NOT EXISTS email_confirmed BOOLEAN DEFAULT FALSE;
-- Lu par /api/digest ; la colonne manquait, la requête échouait donc toujours.
ALTER TABLE profils ADD COLUMN IF NOT EXISTS email_digest BOOLEAN DEFAULT FALSE;
-- Les clés correspondent à celles écrites par /dashboard/notifications.
ALTER TABLE profils ADD COLUMN IF NOT EXISTS notification_prefs JSONB DEFAULT '{"messages":true,"candidatures":true,"offres":true,"kyc":true,"systeme":true}';

-- notifications table
CREATE TABLE IF NOT EXISTS notifications (
  -- BIGINT et non UUID : conforme à la table réellement en production.
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  link TEXT,
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Read own notifications') THEN
    CREATE POLICY "Read own notifications" ON notifications FOR SELECT USING (user_id = auth.uid());
  END IF;
END $$;
-- L'insertion applicative passe par la clé service_role, qui contourne RLS :
-- une policy « WITH CHECK (true) » permettrait à n'importe quel utilisateur
-- authentifié de fabriquer des notifications au nom d'autrui.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Insert notifications') THEN
    CREATE POLICY "Insert notifications" ON notifications FOR INSERT WITH CHECK (
      user_id = auth.uid() OR
      EXISTS (SELECT 1 FROM profils WHERE id = auth.uid() AND role = 'admin')
    );
  END IF;
END $$;

DROP POLICY IF EXISTS "Insert notifications service" ON notifications;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Update own notifications') THEN
    CREATE POLICY "Update own notifications" ON notifications FOR UPDATE USING (user_id = auth.uid());
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(user_id) WHERE read = FALSE;

-- kyc_verifications missing column
ALTER TABLE kyc_verifications ADD COLUMN IF NOT EXISTS nom TEXT;

-- Backfill: copy nom_naissance → nom for existing rows
UPDATE kyc_verifications SET nom = nom_naissance WHERE nom IS NULL AND nom_naissance IS NOT NULL;

-- Drop redundant column (nom = nom de naissance)
ALTER TABLE kyc_verifications DROP COLUMN IF EXISTS nom_naissance;
