-- =====================================================
-- MIGRATION 009 : table des avis
-- =====================================================
--
-- La page /dashboard/secretaire/avis lit et écrit dans une table `avis` qui
-- n'existait ni en base ni dans aucune migration : la lecture échouait en
-- silence (l'erreur n'était pas testée) et chaque envoi d'avis se soldait par
-- un message d'erreur. La fonctionnalité de notation était entièrement morte.
--
-- Le schéma reproduit exactement ce que le code écrit : mission notée, auteur
-- de l'avis, note et commentaire.

CREATE TABLE IF NOT EXISTS avis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mission_id BIGINT NOT NULL REFERENCES missions(id) ON DELETE CASCADE,
  reviewer_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- L'interface attend ce garde-fou : elle traite le code d'erreur 23505
  -- (violation d'unicité) par « Vous avez déjà laissé un avis pour cette
  -- mission ». Sans la contrainte, ce message n'aurait jamais pu s'afficher
  -- et les doublons auraient été acceptés.
  CONSTRAINT avis_unique_par_mission_et_auteur UNIQUE (mission_id, reviewer_id)
);

CREATE INDEX IF NOT EXISTS idx_avis_mission ON avis(mission_id);
CREATE INDEX IF NOT EXISTS idx_avis_reviewer ON avis(reviewer_id);

ALTER TABLE avis ENABLE ROW LEVEL SECURITY;

-- Chacun relit les avis qu'il a rédigés ; les administrateurs voient tout.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Read own avis') THEN
    CREATE POLICY "Read own avis" ON avis FOR SELECT USING (
      reviewer_id = auth.uid() OR public.is_admin()
    );
  END IF;
END $$;

-- On ne peut déposer un avis qu'en son propre nom, et uniquement sur une
-- mission dont on est partie prenante via une offre conclue.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Insert own avis') THEN
    CREATE POLICY "Insert own avis" ON avis FOR INSERT WITH CHECK (
      reviewer_id = auth.uid()
      AND EXISTS (
        SELECT 1 FROM offres o
        WHERE o.mission_id = avis.mission_id
          AND o.statut = 'concluee'
          AND (o.entreprise_id = auth.uid() OR o.secretaire_id = auth.uid())
      )
    );
  END IF;
END $$;

-- Un avis se corrige mais ne se réattribue pas.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Update own avis') THEN
    CREATE POLICY "Update own avis" ON avis FOR UPDATE
      USING (reviewer_id = auth.uid())
      WITH CHECK (reviewer_id = auth.uid());
  END IF;
END $$;
