-- =====================================================
-- MIGRATION 010 : durcissement de l'authentification
-- =====================================================
--
-- Trois objectifs :
--   1. Doter l'application d'un vrai stockage de codes OTP (à usage unique,
--      hachés, expirants, avec compteur de tentatives).
--   2. Journaliser les évènements d'authentification pour détecter le bourrage
--      d'identifiants et alimenter le blocage progressif.
--   3. Refermer trois policies RLS ouvertes à tous introduites en 001 et 003.
--
-- Idempotente et sans prérequis : tout est en CREATE ... IF NOT EXISTS ou
-- DROP ... IF EXISTS, y compris les tables héritées (section 3). Elle
-- s'applique aussi bien sur une base à jour que sur une base où les migrations
-- précédentes n'ont jamais été passées intégralement, et peut être rejouée.
--
-- =====================================================


-- -----------------------------------------------------
-- 1. Codes à usage unique (OTP)
-- -----------------------------------------------------
--
-- Le code n'est JAMAIS stocké en clair : seule une empreinte HMAC-SHA256
-- (poivrée avec AUTH_SECRET côté serveur) est conservée. Une fuite de la base
-- ne permet donc pas de rejouer un code.
--
-- Un code est lié à un couple (email, purpose) et non au seul utilisateur :
-- l'inscription émet un code avant même que la session existe.
CREATE TABLE IF NOT EXISTS otp_codes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  purpose TEXT NOT NULL CHECK (purpose IN ('signup', 'login', 'password_reset', 'email_change')),
  code_hash TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 5,
  consumed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ NOT NULL,
  ip_address TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Recherche du code actif : (email, purpose) filtré sur les non consommés.
CREATE INDEX IF NOT EXISTS idx_otp_codes_lookup
  ON otp_codes (email, purpose, created_at DESC)
  WHERE consumed_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_otp_codes_expiry ON otp_codes (expires_at);

ALTER TABLE otp_codes ENABLE ROW LEVEL SECURITY;

-- Aucune policy : la table n'est accessible qu'à la service role, qui contourne
-- RLS. Les révocations explicites empêchent toute lecture même si une policy
-- permissive était ajoutée par erreur plus tard.
REVOKE ALL ON TABLE otp_codes FROM anon, authenticated;


-- -----------------------------------------------------
-- 2. Journal des évènements d'authentification
-- -----------------------------------------------------
--
-- Alimente le verrouillage progressif (échecs répétés sur la même adresse =
-- blocage temporaire) et permet a posteriori de repérer une campagne de
-- bourrage d'identifiants.
CREATE TABLE IF NOT EXISTS auth_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  event TEXT NOT NULL,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_auth_events_email_time ON auth_events (email, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_events_ip_time ON auth_events (ip_address, created_at DESC);

ALTER TABLE auth_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE auth_events FROM anon, authenticated;


-- -----------------------------------------------------
-- 3. Tables héritées supposées présentes
-- -----------------------------------------------------
--
-- La section 5 durcit trois tables créées par les migrations 001 et 003.
-- `DROP POLICY IF EXISTS ... ON t` et `REVOKE ... ON TABLE t` échouent tous
-- deux si `t` n'existe pas — le `IF EXISTS` porte sur la policy, pas sur la
-- table. Une base où 001/003 n'ont jamais été appliquées intégralement fait
-- donc échouer cette migration sur « relation does not exist ».
--
-- On recrée ici les définitions manquantes, à l'identique de leur migration
-- d'origine. `IF NOT EXISTS` rend l'opération sans effet là où elles existent
-- déjà, et `two_factor_auth` est de toute façon indispensable au parcours de
-- connexion.

CREATE TABLE IF NOT EXISTS audit_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  details TEXT,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at);

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS email_confirmations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  token TEXT UNIQUE NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_confirmations_token ON email_confirmations(token);

ALTER TABLE email_confirmations ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS two_factor_auth (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE NOT NULL,
  secret TEXT NOT NULL,
  method TEXT NOT NULL CHECK (method IN ('totp', 'email')),
  enabled BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_two_factor_auth_user ON two_factor_auth(user_id);

ALTER TABLE two_factor_auth ENABLE ROW LEVEL SECURITY;


-- -----------------------------------------------------
-- 4. Purge des données expirées
-- -----------------------------------------------------
--
-- Sans purge, `otp_codes` conserve indéfiniment des empreintes de codes et
-- `auth_events` grossit sans limite.
CREATE OR REPLACE FUNCTION purge_auth_artifacts()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  DELETE FROM otp_codes WHERE expires_at < NOW() - INTERVAL '1 day';
  DELETE FROM auth_events WHERE created_at < NOW() - INTERVAL '90 days';

  -- Table héritée : la purge ne doit pas échouer si elle a été supprimée
  -- d'une base après le retrait du parcours de confirmation par lien.
  IF to_regclass('public.email_confirmations') IS NOT NULL THEN
    DELETE FROM email_confirmations WHERE expires_at < NOW() - INTERVAL '7 days';
  END IF;
END;
$function$;

REVOKE ALL ON FUNCTION purge_auth_artifacts() FROM anon, authenticated;


-- -----------------------------------------------------
-- 5. Correction : policies ouvertes à tous (migrations 001 et 003)
-- -----------------------------------------------------
--
-- « System manage email confirmations ... FOR ALL USING (true) » n'avait pas de
-- clause TO : le rôle `anon` pouvait donc lire la table entière, y compris les
-- jetons de confirmation d'email encore valides — soit une prise de contrôle de
-- compte à la portée de n'importe quel visiteur muni de la clé publique.
-- Ces jetons ne sont manipulés que par des routes serveur en service role, qui
-- contourne RLS : supprimer la policy ne casse aucun appel légitime.
DROP POLICY IF EXISTS "System manage email confirmations" ON email_confirmations;
REVOKE ALL ON TABLE email_confirmations FROM anon, authenticated;

-- « System insert audit logs ... WITH CHECK (true) » permettait à n'importe
-- quel visiteur d'insérer des lignes arbitraires dans le journal d'audit, donc
-- de le noyer ou d'y injecter de fausses traces. Les écritures légitimes
-- passent toutes par la service role.
DROP POLICY IF EXISTS "System insert audit logs" ON audit_logs;
REVOKE INSERT, UPDATE, DELETE ON TABLE audit_logs FROM anon, authenticated;

-- Les secrets 2FA ne doivent jamais transiter par le client : la policy
-- « Users read own 2FA » exposait la colonne `secret` (graine TOTP) au
-- navigateur du propriétaire, où une XSS suffisait à la voler — et une graine
-- TOTP volée permet de générer indéfiniment des codes valides.
--
-- On garde une lecture de sa propre ligne, mais restreinte aux colonnes non
-- sensibles via un GRANT au niveau colonne. Les écritures passent
-- exclusivement par les routes serveur en service role.
DROP POLICY IF EXISTS "Users read own 2FA" ON two_factor_auth;
DROP POLICY IF EXISTS "Users update own 2FA" ON two_factor_auth;
DROP POLICY IF EXISTS "Users insert own 2FA" ON two_factor_auth;
REVOKE ALL ON TABLE two_factor_auth FROM anon, authenticated;

ALTER TABLE two_factor_auth ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

DROP POLICY IF EXISTS "Users read own 2FA status" ON two_factor_auth;
CREATE POLICY "Users read own 2FA status" ON two_factor_auth
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

GRANT SELECT (user_id, method, enabled, updated_at) ON two_factor_auth TO authenticated;


-- -----------------------------------------------------
-- 6. Appareils de confiance (préparation)
-- -----------------------------------------------------
--
-- Le produit exige aujourd'hui un OTP à chaque connexion. Cette table permet
-- de basculer plus tard sur un modèle adaptatif (OTP seulement sur un appareil
-- inconnu) sans nouvelle migration : voir ARCHITECTURE.md.
CREATE TABLE IF NOT EXISTS trusted_devices (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  device_hash TEXT NOT NULL,
  label TEXT,
  last_used_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, device_hash)
);

ALTER TABLE trusted_devices ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE trusted_devices FROM anon;

DROP POLICY IF EXISTS "Users read own devices" ON trusted_devices;
CREATE POLICY "Users read own devices" ON trusted_devices
  FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users revoke own devices" ON trusted_devices;
CREATE POLICY "Users revoke own devices" ON trusted_devices
  FOR DELETE TO authenticated USING (auth.uid() = user_id);
